--Aritméticos
    +(soma), 
    -(subtração),
    *(multiplicação),
    /(divisão),
    **(potenciação)

-- Lógicos
    AND(E Lógico),
    OR(Ou Lógico),
    NOT(Não Lógico)

--Relecionais
    =(Igual a),
    <>,!=,~=(Diferente),
    >(Maior que),
    >=(Maior ou igual a),
    <(Menor que),
    <=(Menor ou igual a)

--Comparação
    BETWEEN(entre dois valores),
    LIKE(conparação com carqacter curinga)

--Atribuição
    :=

--Concatenação
    ||

--Rótulo
    <<Rótulo>>