// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcYWbqM1TfJBCIGH8vfebpL21WC5nVCe8',
    appId: '1:621678443612:web:fa550880f0ce45317dba99',
    messagingSenderId: '621678443612',
    projectId: 'myfirebase-82a0d',
    authDomain: 'myfirebase-82a0d.firebaseapp.com',
    storageBucket: 'myfirebase-82a0d.firebasestorage.app',
    measurementId: 'G-ZZ6JBP6F03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAg9KjtW2UfMbElI-wp3rlGXHS1iIezwk',
    appId: '1:621678443612:android:988462f485264e3d7dba99',
    messagingSenderId: '621678443612',
    projectId: 'myfirebase-82a0d',
    storageBucket: 'myfirebase-82a0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmjYfFCd9vA-lmqEfAMm51Cd7zmD73UVY',
    appId: '1:621678443612:ios:0e929ab8cdbb74ca7dba99',
    messagingSenderId: '621678443612',
    projectId: 'myfirebase-82a0d',
    storageBucket: 'myfirebase-82a0d.firebasestorage.app',
    iosBundleId: 'com.example.googleCloudMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmjYfFCd9vA-lmqEfAMm51Cd7zmD73UVY',
    appId: '1:621678443612:ios:0e929ab8cdbb74ca7dba99',
    messagingSenderId: '621678443612',
    projectId: 'myfirebase-82a0d',
    storageBucket: 'myfirebase-82a0d.firebasestorage.app',
    iosBundleId: 'com.example.googleCloudMessaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcYWbqM1TfJBCIGH8vfebpL21WC5nVCe8',
    appId: '1:621678443612:web:c25ac24246e041177dba99',
    messagingSenderId: '621678443612',
    projectId: 'myfirebase-82a0d',
    authDomain: 'myfirebase-82a0d.firebaseapp.com',
    storageBucket: 'myfirebase-82a0d.firebasestorage.app',
    measurementId: 'G-1227QVYZ7W',
  );
}
