Algoritmo "Tomada de Decisão - SE"
// Disciplina  : Lógica de Programação
// Professor   : Franklin Portela
// Autor(a)    : Willian Ferreira Gomes
// Data atual  : 15/04/2024
Var
n1, n2: inteiro

Inicio

escreval("Tomada de Decisão - SE")
escreval
escreva("Digite o primeiro numero: ")
leia(n1)
escreva("Digite o segundo numero: ")
leia(n2)

se(n1>n2)entao
     escreval("O primeiro numero é maior")
senao
     escreval("O segundo numero é maior")
fimse

Fimalgoritmo