Algoritmo "Procedimento Multiplicação"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Lucy Mari
// Autor(a)    : Willian Ferreira
// Data atual  : 13/05/2024

var
//Variaveis Globais
   Procedimento mostreNaTela(frase: caracter)
   var
   inicio
         escreva(frase)
   fimprocedimento

Inicio
      Escreval("Mensangem do procedimento:")
      mostreNaTela("Meu Primeiro Procedimento com Parâmetro!!!")
Fimalgoritmo